### ISSUE TITLE
Mutli channel funnel API

### ISSUE THREAD

**Issue by erikdung** [jsguy/ga-api#2]
Hi,
I tried to query for mcf:totalConversions, but got error. Please help.

**Comment by kitfit-mikkel** [comment]
Sorry, I'm not sure how to help with that, did you check the documentation here?:

https://developers.google.com/analytics/devguides/reporting/mcf/v3/reference

**Comment by jsguy** [comment]
Sorry, I'm not sure how to help with that, did you check the documentation here?:

https://developers.google.com/analytics/devguides/reporting/mcf/v3/reference
